version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - "8081:8080"

  kafka-producer-app:
      image: kafka-producer-app
      build: ./producer
      ports:
        - 3000:3000
        - 9229:9229
      depends_on:
        - kafka
      environment:
        KAFKA_BROKERS: kafka:9092
      command: node --inspect=0.0.0.0:9229 server.js

  kafka-websockets-app:
    image: kafka-websockets-app
    build: ./websockets
    ports:
      - 8082:8082
      - 9230:9229
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092
    command: node --inspect=0.0.0.0:9229 webSocketServer.js

  frontend:
    build: ./frontend
    ports:
      - "3001:80"
